project:
  type: website

website:
  title: "PyData Natal"
  google-analytics: G-QW559WNCMG
  page-navigation: true
  cookie-consent: true
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/PyData-Natal
      - icon: discord
        href: https://www.meetup.com/pydata-natal/
format:
  html:
    theme: 
      light: flatly
      #dark: darkly
    css: styles.css
    toc: true
    toc-location: left



